import LegalPage from "@/components/common/LegalPage";

export default function Privacy() {
  return (
    <LegalPage
      title="Privacy Policy"
      subtitle="This policy explains what personal data PARYAJ 888 collects, how we use it, and the choices you have regarding your information."
      lastUpdated="August 1, 2026"
      sections={[
        {
          heading: "Information We Collect",
          body: "We collect information you provide directly, such as your name, email, date of birth, and address when you register. We also collect data generated by your use of the Service, including bet history, device information, and IP address.",
          list: [
            "Identity data: name, date of birth, nationality.",
            "Contact data: email address, phone number, postal address.",
            "Financial data: payment method identifiers (we do not store full card numbers).",
            "Usage data: bets placed, pages viewed, login times, device and browser data.",
          ],
        },
        {
          heading: "How We Use Your Information",
          list: [
            "To create and manage your account and verify your identity (KYC).",
            "To process deposits, bets, and withdrawals.",
            "To detect and prevent fraud, money laundering, and bonus abuse.",
            "To communicate with you about your account, changes, and responsible gaming.",
            "To comply with legal and regulatory obligations.",
          ],
        },
        {
          heading: "Legal Basis for Processing",
          body: "We process your personal data on the basis of contract performance (account and betting services), legal compliance (AML and regulatory requirements), and our legitimate interests in operating a secure platform. Where we rely on consent, you may withdraw it at any time.",
        },
        {
          heading: "Cookies & Tracking",
          body: "We use cookies and similar technologies to keep you logged in, remember preferences, and analyze platform usage. You can control cookies through your browser settings. Essential cookies are required for the Service to function.",
        },
        {
          heading: "Sharing of Information",
          body: "We do not sell your personal data. We may share it with:",
          list: [
            "Payment processors and providers that enable deposits and withdrawals.",
            "Identity verification and fraud-screening services.",
            "Regulators and law enforcement where legally required.",
            "Cloud and infrastructure providers that host and secure the Service.",
          ],
        },
        {
          heading: "Data Security",
          body: "We use industry-standard safeguards including encryption in transit and at rest, access controls, and monitoring to protect your data. No system is perfectly secure; we continuously work to reduce risk, but we cannot guarantee absolute security.",
        },
        {
          heading: "Data Retention",
          body: "We retain your personal data for as long as your account is active and for a period thereafter as required by law, particularly for AML record-keeping which may extend to several years after account closure.",
        },
        {
          heading: "Your Rights",
          list: [
            "Access: request a copy of the personal data we hold about you.",
            "Correction: request that inaccurate data be corrected.",
            "Erasure: request deletion where legally permitted.",
            "Restriction and objection: limit or object to certain processing.",
            "Portability: receive your data in a structured, machine-readable format.",
          ],
        },
        {
          heading: "Children's Privacy",
          body: "The Service is strictly for adults of legal gambling age. We do not knowingly collect data from minors. If you believe a minor has registered, contact Support immediately so we can investigate and remove the account.",
        },
        {
          heading: "International Transfers",
          body: "Your data may be processed in countries other than your own. Where this occurs, we ensure appropriate safeguards are in place, such as standard contractual clauses, to protect your data in line with this policy.",
        },
        {
          heading: "Changes to This Policy",
          body: "We may update this Privacy Policy from time to time. We will notify you of significant changes through the platform or by email. The 'Last updated' date reflects when the policy was last revised.",
        },
      ]}
    />
  );
}